### ISSUE TITLE
Does anybody have this working with Tesla Style Solar Power Card?

### ISSUE THREAD

**Issue by LukePrior** [binsentsu/home-assistant-solaredge-modbus#55]
Hi,

I have configured this integration and can see the values in the energy dashboard however I want to setup a live view with the Tesla Style Power [card](https://github.com/reptilex/tesla-style-solar-power-card). I have run into difficulties in finding what values to use and what templating is necessary. I would appreciate if anyone who has these two things setup and working correctly could post their configuration details.

I think @mpredfearn has this working looking at previous posts.

EDIT:

This configuration worked for me with a simple system with no battery.

**Tesla Card:**

```
type: custom:tesla-style-solar-power-card
house_entity: sensor.power_consumption
grid_entity: sensor.solaredge_m1_ac_power
generation_entity: sensor.solaredge_ac_power
grid_to_house_entity: sensor.power_grid_import
generation_to_grid_entity: sensor.power_grid_export
generation_to_house_entity: sensor.power_self_consumption
```

**Template:**

```
sensor:                                                                         
  - platform: template                                                          
    sensors:
      power_grid_import:                                                    
        friendly_name: "Power - Grid Import"                                    
        unit_of_measurement: "W"                                                
        value_template: "{{ (states('sensor.solaredge_m1_ac_power') | float | min(0) | abs()) }}"
      power_grid_export:                                                     
        friendly_name: "Power - Grid Export"                                    
        unit_of_measurement: "W"                                                
        value_template: "{{ states('sensor.solaredge_m1_ac_power') | float | max(0) | abs() }}"                                                                                                                                                   
      power_consumption:                                                  
        friendly_name: "Power - Consumption"                                    
        unit_of_measurement: "W"                                                
        value_template: "{{ (states('sensor.solaredge_ac_power') | float | max(0)) - (states('sensor.solaredge_m1_ac_power') | float) }}"
      power_self_consumption:                                            
        friendly_name: "Power - Self Consumption"                               
        unit_of_measurement: "W"                                                
        value_template: "{{ (states('sensor.solaredge_ac_power') | float | max(0)) - states('sensor.power_grid_export') | float}}"     
```

**Comment by mpredfearn** [comment]
In an ideal world, I think the templated sensors should be provided by the integration, but that gets very complex very fast due to the variations in peoples systems:
- Presence / absence of meters
- Presence / absence of batteries
- Configuration (location) of meters i.e. grid connection / load connection point
All of these completely change the maths that has to be performed to come up with the right power flows. Maybe I'll feel like sitting down and writing all of that one day, but it's quite a big task....

**Comment by LukePrior** [comment]
Hey,

Thanks for providing your configuration, I see you have a battery configured so I have tried to remove that bit and get it all working.

Tesla Card:

```
type: custom:tesla-style-solar-power-card
house_entity: sensor.power_consumption
grid_entity: sensor.solaredge_modbus_m1_ac_power
generation_entity: sensor.solaredge_modbus_i1_ac_power
grid_to_house_entity: sensor.power_grid_import
generation_to_grid_entity: sensor.power_grid_export
generation_to_house_entity: sensor.power_self_consumption
```

Template

```
sensor:                                                                         
  - platform: template                                                          
    sensors:
      power_grid_import:                                                    
        friendly_name: "Power - Grid Import"                                    
        unit_of_measurement: "W"                                                
        value_template: "{{ (states('sensor.solaredge_modbus_m1_ac_power') | float | min(0) | abs()) }}"
      power_grid_export:                                                     
        friendly_name: "Power - Grid Export"                                    
        unit_of_measurement: "W"                                                
        value_template: "{{ states('sensor.solaredge_modbus_m1_ac_power') | float | max(0) | abs() }}"                                                                                                                                                   
      power_consumption:                                                  
        friendly_name: "Power - Consumption"                                    
        unit_of_measurement: "W"                                                
        value_template: "{{ (states('sensor.solaredge_modbus_i1_ac_power') | float | max(0)) - (states('sensor.solaredge_modbus_m1_ac_power') | float) }}"
      power_self_consumption:                                            
        friendly_name: "Power - Self Consumption"                               
        unit_of_measurement: "W"                                                
        value_template: "{{ (states('sensor.solaredge_modbus_i1_ac_power') | float | max(0)) - states('sensor.power_grid_export') | float}}" 
```

I'm not having much luck, however:

![image](https://user-images.githubusercontent.com/22492406/136531321-0471c8bb-1d36-47b9-8537-24b712f5d430.png)
![image](https://user-images.githubusercontent.com/22492406/136531366-9c367ea0-0e09-46f8-9ce3-aca3da1510c7.png)

This is my first time getting Home Assistant setup so I'm not sure what's going wrong.
