### ISSUE TITLE
Wiki: typo in config for TeslaStylePowerCard

### ISSUE THREAD

**Issue by ChristophCaina** [binsentsu/home-assistant-solaredge-modbus#61]
There's a small issue with the configuration.yaml for the Power Flow...

```
power_self_consumption:                                            
        friendly_name: "Power - Self Consumption"                               
        unit_of_measurement: "W"           
        # Self consumption of solar generation is inverter output, minus what is being exported to grid                                 
        value_template: "{{ (states('sensor.solaredge_modbus_i1_ac_power') | float)) - states('sensor.power_grid_export') | float}}" 
```

should be:
```
power_self_consumption:                                            
        friendly_name: "Power - Self Consumption"                               
        unit_of_measurement: "W"           
        # Self consumption of solar generation is inverter output, minus what is being exported to grid                                 
        value_template: "{{ (states('sensor.solaredge_modbus_i1_ac_power') | float) - (states('sensor.power_grid_export') | float) }}" 
```

Additionally, the flow is going from "Home" to "Solar" instead of "Solar" to "Home"
![grafik](https://user-images.githubusercontent.com/26391061/138082910-b9203aeb-6bd6-479e-83ed-2cfb4e24462e.png)
